Feat/119
unb-mds/Gastos-DF-2024-02 pull request #134
Opened 2024-12-28 13:42 UTC by johnaopedro

---
# Criação dos scripts de automação
---

## Descrição

Criei os scripts de automação de coleta da API.

## Tipo de mudança

- [ ] Correção de bug
- [x] Nova funcionalidade
- [ ] Alteração de funcionalidade existente
- [ ] Refatoração de código
- [ ] Atualização de documentação

## Issue Relacionada

Se desejar fechar uma issue, escreva neste padrão:
- closes #119

## Questões em aberto

É necessário ver o comportamento que terá o script no github action.

## Checklist

- [x] O código segue as diretrizes do repositório
- [x] O código foi testado
- [ ] A documentação foi atualizada

2024-12-30 14:18 UTC, Nibaacriba requested changes

2024-12-30 14:18 UTC, Nibaacriba commented on actions/notasfiscais.py
Tem que tirar esse arquivo, já que não vamos utilizar mais.

2024-12-30 23:57 UTC, johnaopedro commented
A remoção foi efetuada.

2024-12-31 11:53 UTC, Nibaacriba approved these changes

2025-01-03 23:14 UTC, merged