Requisitos
unb-mds/Gastos-DF-2024-02 pull request #2
Opened 2024-11-01 13:37 UTC by JuliaGabP

2024-11-01 20:26 UTC, JuliaGabP commented
Fechado para atualizações.

2024-11-01 21:21 UTC, Nibaacriba commented on trabalho_teoria/requisitos/requisitos_iniciais.md
>  - Incluir dados atualizados e categorizaados por setor;
`categorizados` está escrito errado.

2024-11-01 21:29 UTC, Nibaacriba requested changes
Corrija os pontos levantados. De resto, parabéns.

2024-11-01 21:29 UTC, Nibaacriba commented on trabalho_teoria/requisitos/requisitos_iniciais.md
> +- Informar um guia de uso para mostrar como navegar e utilizar as funcionalidades.
Aqui talvez seja melhor utilizar outra palavra? **Informar** me parece errado nesse contexto. **disponibilizar** me parece mais adequado.

2024-11-01 22:29 UTC, JuliaGabP commented
Fechado para correções

2024-11-02 16:03 UTC, Nibaacriba approved these changes

2024-11-02 16:03 UTC, merged