Feat/67
unb-mds/Gastos-DF-2024-02 pull request #73
Opened 2024-11-28 03:28 UTC by BrzGab

- codificação da responsividade do site.
- [issue #67](https://github.com/unb-mds/Squad13/issues/67)

2024-11-28 13:47 UTC, Nibaacriba requested changes
Vejam se retirar o recuo das listas para os dispositivos móveis é muito trabalhoso. se não for, acredito que seja uma boa fazer isso, já que no desktop esse recuo funciona pois temos bastante espaço de tela para trabalhar.
<img width="269" alt="Captura de Tela 2024-11-28 às 10 45 18" src="https://github.com/user-attachments/assets/79e98969-ab73-427a-909b-df6ab8467d9c">

2024-11-28 13:47 UTC, Nibaacriba commented on codigo/project/static/css/style.css
> +  .barra-navegacao {
`barra-navegacao` não precisa de `flex-direction: column` para esse tamanho de tela. Testei no tablet e nos celulares em modo paisagem. Acredito que o botão fica muito grande, e a barra de navegação acaba ocupando um espaço desnecessário.

2024-11-28 23:58 UTC, BrzGab commented on codigo/project/static/css/style.css
> +  .barra-navegacao {
O código foi ajustado, alterando o flex-direction para row para uma melhor adequação ao tamanho da tela. Além disso, o recuo das listas foi ajustado.

2024-11-29 00:21 UTC, Nibaacriba approved these changes

2024-11-29 13:11 UTC, ArtyMend07 approved these changes

2024-11-30 00:13 UTC, JuliaGabP approved these changes

2024-11-30 00:23 UTC, johnaopedro approved these changes

2024-11-30 02:04 UTC, merged