Documentacao da Sprint 3
unb-mds/Gastos-DF-2024-02 pull request #74
Opened 2024-11-28 04:02 UTC by lucasarruda9

issue #71

2024-11-28 13:19 UTC, Nibaacriba commented on documentacao/sprints/sprint3.md
> +Com o adiamento de diversos requisitos da sprint 2, foi decidido na Sprint 3 o foco na documentação e na personalização do front-end com Figma para garantir um bom andamento nas sprints futuras.
aqui deveria ser `adiantamento`, não? Adiamento é o processo de postergar algo, deixar pra depois.

2024-11-28 13:22 UTC, Nibaacriba commented on documentacao/sprints/sprint3.md
> +2. **Requisito R14:** Publicar no Github Pages, uma plataforma gratuita que permite hospedar páginas estáticas diretamente de um repositório do GitHub.
Aqui você esqueceu de adicionar também a criação da release notes

2024-11-28 13:23 UTC, Nibaacriba requested changes
Corrija os pontos mencionados.

2024-11-28 13:38 UTC, lucasarruda9 commented
fechando pull request para correções

2024-11-28 15:42 UTC, JuliaGabP requested changes

2024-11-28 15:42 UTC, JuliaGabP commented on documentacao/sprints/sprint3.md
> +| R10 | Conectar Front-end ao Back-end             | Alta 🔴       | Não iniciado  |
Requisito já concluído na sprint 2

2024-11-28 15:42 UTC, JuliaGabP commented on documentacao/sprints/sprint3.md
> +| R12 | Adicionar Gráficos com Dados Estáticos     | Média 🟡      | Não iniciado  |
Requisito já concluíso na sprint 2

2024-11-28 15:43 UTC, JuliaGabP commented
Corrigir os status dos requisitos 10 e 12 para concluídos.

2024-11-29 13:30 UTC, johnaopedro requested changes
Corrigir apenas as mudanças apontadas pela @JuliaGabP

2024-11-29 19:58 UTC, lucasarruda9 commented
pull request fechado para correções

2024-11-29 22:30 UTC, Nibaacriba approved these changes

2024-11-30 00:11 UTC, JuliaGabP approved these changes

2024-11-30 00:20 UTC, johnaopedro approved these changes

2024-11-30 00:38 UTC, merged