doc/93
unb-mds/Gastos-DF-2024-02 pull request #95
Opened 2024-12-04 20:48 UTC by lucasarruda9

criação do CODE_OF_CONDUCT

2024-12-04 21:53 UTC, johnaopedro commented
O documento está padronizado em português. Favor alterar o idioma.

2024-12-04 21:54 UTC, johnaopedro requested changes
A documentação está padronizada em português. Favor alterar o idioma.

2024-12-04 21:57 UTC, lucasarruda9 commented
PR fechado para alteração no idioma

2024-12-04 23:29 UTC, johnaopedro requested changes

2024-12-04 23:29 UTC, johnaopedro commented on CODE_OF_CONDUCT.md
> +* Dar e receber feedbacks construtivos de maneira respeitosa
Mantenha apenas 'feedback', em vez de 'feedbacks'.

2024-12-04 23:29 UTC, johnaopedro commented on CODE_OF_CONDUCT.md
> +**Impacto na comunidade**: Uso de linguagem imprópria ou outro comportamento considerado anti-profissional ou repudiado pela comunidade.
Use apenas:
"Uso de linguagem imprópria ou comportamento anti-profissional, considerado pela comunidade."

Esse: "outro comportamento" é desnecessário.

2024-12-05 02:12 UTC, johnaopedro approved these changes

2024-12-05 14:58 UTC, ArtyMend07 approved these changes

2024-12-05 14:59 UTC, merged