doc/93-2
unb-mds/Gastos-DF-2024-02 pull request #96
Opened 2024-12-04 20:59 UTC by lucasarruda9

criação da política de segurança

2024-12-04 21:50 UTC, JuliaGabP requested changes
Inserir um complemento, a política de segurança se encontra muito rasa;
Deixar informado para o usuário o email que o mesmo deve entrar em contato, não consegui encontra-lo, caso já informado, desconsiderar.

2024-12-04 22:31 UTC, lucasarruda9 commented
PR fechado para modificação

2024-12-05 02:47 UTC, johnaopedro approved these changes

2024-12-05 15:36 UTC, JuliaGabP approved these changes

2024-12-05 15:36 UTC, merged